/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Samples */
        get: operations["get_samples_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Policy */
        post: operations["ingest_policy_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_policies__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{id}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Policy Terms */
        put: operations["update_policy_terms_policies__id__terms_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Bill */
        post: operations["upload_bill_bills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Confirm Run */
        put: operations["confirm_run_runs__id__confirm_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Stream */
        get: operations["run_stream_runs__id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Events */
        get: operations["get_run_events_runs__id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Result */
        get: operations["get_run_result_runs__id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Demo */
        post: operations["run_demo_demo__sample_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionPack */
        ActionPack: {
            /** Desk Questions */
            desk_questions: components["schemas"]["DeskQuestion"][];
            letter: components["schemas"]["Letter"];
            /** Checklist */
            checklist: string[];
        };
        /** BillLine */
        BillLine: {
            /** Line No */
            line_no: number;
            /** Raw Text */
            raw_text: string;
            /** Qty */
            qty?: number | null;
            /** Unit Price */
            unit_price?: number | null;
            /** Amount */
            amount: number;
            /** Service Date */
            service_date?: string | null;
            /** Category Guess */
            category_guess?: ("room" | "nursing" | "professional_fee" | "procedure" | "pharmacy" | "consumable" | "investigation" | "implant" | "other") | null;
        };
        /** ConfirmRunRequest */
        ConfirmRunRequest: {
            /** Lines */
            lines: components["schemas"]["MatchedLine"][];
            /** Is Insured */
            is_insured: boolean;
        };
        /** DeskQuestion */
        DeskQuestion: {
            /** Priority */
            priority: number;
            /** Question */
            question: string;
            /** Why */
            why: string;
            /**
             * Line Ids
             * @default []
             */
            line_ids: number[];
            /** Amount */
            amount?: number | null;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "line" | "clause" | "catalog" | "calc" | "kb";
            /** Text */
            text: string;
            /**
             * Meta
             * @default {}
             */
            meta: {
                [key: string]: unknown;
            };
        };
        /** ExtractedBill */
        ExtractedBill: {
            /** Hospital Name */
            hospital_name?: string | null;
            /** Bill Date */
            bill_date?: string | null;
            /** Stated Total */
            stated_total?: number | null;
            /** Estimate Amount */
            estimate_amount?: number | null;
            /** Lines */
            lines: components["schemas"]["BillLine"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** Finding */
        Finding: {
            /** Id */
            id: string;
            /** Rule Code */
            rule_code: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "billing" | "coverage";
            /**
             * Severity
             * @enum {string}
             */
            severity: "red" | "amber" | "info";
            /**
             * Origin
             * @enum {string}
             */
            origin: "rule" | "agent";
            /**
             * Line Ids
             * @default []
             */
            line_ids: number[];
            /** Title */
            title: string;
            /** Explanation */
            explanation: string;
            /** Amount At Stake */
            amount_at_stake?: number | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /** Suggested Question */
            suggested_question?: string | null;
            /**
             * Uncertain
             * @default false
             */
            uncertain: boolean;
            /** Agent Note */
            agent_note?: string | null;
            /**
             * Dismissed
             * @default false
             */
            dismissed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Letter */
        Letter: {
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /**
             * Generated By
             * @enum {string}
             */
            generated_by: "template" | "llm";
        };
        /** MatchedLine */
        MatchedLine: {
            /** Line No */
            line_no: number;
            /** Raw Text */
            raw_text: string;
            /** Qty */
            qty?: number | null;
            /** Unit Price */
            unit_price?: number | null;
            /** Amount */
            amount: number;
            /** Service Date */
            service_date?: string | null;
            /** Category Guess */
            category_guess?: ("room" | "nursing" | "professional_fee" | "procedure" | "pharmacy" | "consumable" | "investigation" | "implant" | "other") | null;
            /** Catalog Id */
            catalog_id?: number | null;
            /** Canonical Name */
            canonical_name?: string | null;
            /** Category */
            category?: ("room" | "nursing" | "professional_fee" | "procedure" | "pharmacy" | "consumable" | "investigation" | "implant" | "other") | null;
            /**
             * Match Method
             * @default unmatched
             * @enum {string}
             */
            match_method: "exact" | "embedding" | "llm" | "unmatched";
            /** Match Score */
            match_score?: number | null;
            /**
             * Extraction Flag
             * @default false
             */
            extraction_flag: boolean;
            /**
             * User Edited
             * @default false
             */
            user_edited: boolean;
        };
        /** PolicyTerm */
        PolicyTerm: {
            /**
             * Key
             * @enum {string}
             */
            key: "sum_insured" | "room_rent_cap" | "copay_pct" | "proportionate_deduction";
            /**
             * Status
             * @enum {string}
             */
            status: "extracted" | "manual" | "not_found";
            /** Value */
            value?: number | boolean | null;
            /** Room Cap Kind */
            room_cap_kind?: ("absolute" | "pct_si") | null;
            /** Quote */
            quote?: string | null;
            /** Page */
            page?: number | null;
            /** Chunk Id */
            chunk_id?: number | null;
            /** Similarity */
            similarity?: number | null;
        };
        /** PolicyTermsUpdate */
        PolicyTermsUpdate: {
            /** Terms */
            terms: {
                [key: string]: unknown;
            };
            /** Confirmed */
            confirmed: boolean;
        };
        /** ResolvedPolicy */
        ResolvedPolicy: {
            /** Is Insured */
            is_insured: boolean;
            /** Sum Insured */
            sum_insured?: number | null;
            /** Room Rent Cap Per Day */
            room_rent_cap_per_day?: number | null;
            /**
             * Copay Pct
             * @default 0
             */
            copay_pct: number;
            /**
             * Proportionate Deduction
             * @default false
             */
            proportionate_deduction: boolean;
            /**
             * Term Evidence
             * @default {}
             */
            term_evidence: {
                [key: string]: string;
            };
        };
        /** RunRequest */
        RunRequest: {
            /** Bill Id */
            bill_id: string;
            /** Policy Id */
            policy_id?: string | null;
            /** Auto Confirm */
            auto_confirm?: boolean | null;
        };
        /** RunResult */
        RunResult: {
            /** Run Id */
            run_id: string;
            bill: components["schemas"]["ExtractedBill"];
            /** Lines */
            lines: components["schemas"]["MatchedLine"][];
            /**
             * Policy Terms
             * @default {}
             */
            policy_terms: {
                [key: string]: components["schemas"]["PolicyTerm"];
            };
            policy: components["schemas"]["ResolvedPolicy"];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            simulator: components["schemas"]["SimulatorResult"];
            summary: components["schemas"]["Summary"];
            action_pack?: components["schemas"]["ActionPack"] | null;
            /**
             * Mode
             * @default live
             * @enum {string}
             */
            mode: "live" | "replay";
        };
        /** Sample */
        Sample: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Thumb Url */
            thumb_url: string;
            /** Is Insured */
            is_insured: boolean;
        };
        /** SimulatorResult */
        SimulatorResult: {
            /** Applied */
            applied: boolean;
            /** Billed Total */
            billed_total: number;
            /**
             * Non Payable Total
             * @default 0
             */
            non_payable_total: number;
            /**
             * Room Rent Deduction
             * @default 0
             */
            room_rent_deduction: number;
            /**
             * Copay Amount
             * @default 0
             */
            copay_amount: number;
            /** Insurer Pays */
            insurer_pays: number;
            /** Patient Pays */
            patient_pays: number;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["WaterfallStep"][];
            /**
             * Assumptions
             * @default []
             */
            assumptions: string[];
        };
        /** Summary */
        Summary: {
            /** Billed Total */
            billed_total: number;
            /** Questionable Total */
            questionable_total: number;
            /** Insurer Deductions Total */
            insurer_deductions_total: number;
            /** Insurer Pays */
            insurer_pays: number | null;
            /** Patient Pays */
            patient_pays: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Agent Stats
             * @default {}
             */
            agent_stats: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaterfallStep */
        WaterfallStep: {
            /**
             * Key
             * @enum {string}
             */
            key: "billed" | "non_payable" | "room_rent" | "copay" | "sum_insured_cap" | "insurer_pays" | "patient_pays";
            /** Label */
            label: string;
            /** Amount */
            amount: number;
            /** Running Total */
            running_total: number;
            /** Explanation */
            explanation: string;
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_samples_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sample"][];
                };
            };
        };
    };
    ingest_policy_policies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_policy_policies__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_terms_policies__id__terms_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyTermsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedPolicy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_bill_bills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_run_runs__id__confirm_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_stream_runs__id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_runs__id__events_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_result_runs__id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_demo_demo__sample_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
